# Generated by Django 5.0.4 on 2024-05-22 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitcardorder',
            name='post_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 5, 22, 17, 43, 22, 734912, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
