# Generated by Django 5.0.4 on 2024-05-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_qrcode', '0002_visitcardorder_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitcardorder',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
