# Generated by Django 5.0.4 on 2024-05-22 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0003_tabcard_description1'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description1',
            field=models.CharField(default=datetime.datetime(2024, 5, 22, 4, 59, 46, 606636, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
