# Generated by Django 5.0.4 on 2024-05-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0004_book_description1_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='views_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
