# Generated by Django 5.0.4 on 2024-05-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0005_book_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='description1',
            field=models.TextField(),
        ),
    ]
