# Generated by Django 5.0.4 on 2024-05-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0006_alter_book_description_alter_book_description1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='post',
            field=models.CharField(max_length=100),
        ),
    ]
