# Generated by Django 5.0.4 on 2024-05-19 14:11

import app3_user.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app2_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='engagement_images/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(choices=[('nepal', 'Nepal'), ('india', 'India'), ('usa', 'USA')], default='nepal', max_length=50)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('cv_or_resume', models.FileField(upload_to=app3_user.models.upload_to_jobapplication)),
                ('photo', models.FileField(upload_to=app3_user.models.upload_to_jobapplication)),
                ('cover_letter', models.FileField(upload_to=app3_user.models.upload_to_jobapplication)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('relocate_to_pune', models.BooleanField(default=False)),
                ('additional_question', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2_data.job_vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='ContactFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(choices=[('nepal', 'Nepal'), ('india', 'India'), ('usa', 'USA')], default='nepal', max_length=5)),
                ('phone_number', models.CharField(max_length=20)),
                ('project_description', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('engagement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3_user.engagementchoice')),
                ('services_needed', models.ManyToManyField(to='app3_user.service')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
