
name: React.js CII
on: 
  push: 
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build: 
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - run: pnpm i
      - run: | 
          echo "${{ secrets.ENV_FILE}}" > .env
      - run: pnpm build
